Repository netcup-community/community-tutorials, pull requests merged in 2021-12, with the labels that each got.

#31 Add tutorial for a dockerized cs:go dedicated server
  community-tutorials/dockerized-csgo-gameserver/01-en.md
Labels: Language Check

#60 Install NodeJS with NPM (reopen #20)
  community-tutorials/install-nodejs-with-npm/01-en.md
Labels: review

#38 Squid Proxy Tutorial
  community-tutorials/squid/01-en.md
Labels: invalid
